### ISSUE TITLE
Cannot build release

### ISSUE THREAD

**Issue by atoponce** [julianandrews/markovpass#4]
The following error happens when attempting to compile:

    % cargo build --release
      Downloaded rand_chacha v0.2.2
      Downloaded unicode-width v0.1.5
      Downloaded libc v0.2.69
      Downloaded getopts v0.2.18
      Downloaded 4 crates (519.8 KB) in 7.06s
       Compiling libc v0.2.69
       Compiling getrandom v0.1.14
       Compiling cfg-if v0.1.10
       Compiling ppv-lite86 v0.2.6
       Compiling unicode-width v0.1.5
       Compiling getopts v0.2.18
       Compiling rand_core v0.5.1
       Compiling rand_chacha v0.2.2
       Compiling rand v0.7.3
       Compiling markovpass v1.0.1 (/home/aaron/src/markovpass)
    error[E0554]:  may not be used on the stable release channel
     --> src/main.rs:1:1
      |
    1 | #![feature(test)]
      | ^^^^^^^^^^^^^^^^^
    
    error: aborting due to previous error
    
    For more information about this error, try Feature attributes are only allowed on the nightly release channel. Stable or
    beta compilers will not comply.
    
    Erroneous code example:
    
    ```
    #![feature(non_ascii_idents)] // error: `#![feature]` may not be used on the
                                  //        stable release channel
    ```
    
    If you need the feature, make sure to use a nightly release of the compiler
    (but be warned that the feature may be removed or altered in the future)..
    error: could not compile .
    
    To learn more, run the command again with --verbose.

Commenting out `#![feature(test)]` from `src/main.rs` and `extern crate test;` from `src/lib/mod.rs` allows the build to succeed.

**Comment by julianandrews** [comment]
I need to dig into this. Last I checked the `#[feature(test)]` is required for the benchmarking code to work, but I guess it only works on nightly.

So for the moment, I guess this only works on nightly. It probably doesn't make sense to require nightly just for the benchmarking though. I'll see what I can do!

**Comment by julianandrews** [comment]
Ok! This should be fixed. I ended up gating the benchmarking code behind a feature so that it can be manually run using `cargo bench --feature benchmarks`, but the benchmarking support won't get built by default.

I would like a way to make the gating automatic on being on nightly, but it looks as if there's not a good option for that.
